name: travinia
description: A Booking Flutter project to book hotels.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: null
  blur: ^3.1.0
  carousel_slider: ^4.1.1
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: null
  dot_navigation_bar: ^1.0.1+4
  email_validator: ^2.1.17
  equatable: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  font_awesome_flutter: null
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  internet_connection_checker: null
  password_strength: ^0.2.0
  permission_handler: ^10.0.1
  readmore: ^2.2.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo_dark.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
        - weight: 300
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
