name: travinia
description: A Booking Flutter project to book hotels.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc:
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio:
  email_validator: ^2.1.17
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc: null
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.4
  font_awesome_flutter: null
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  internet_connection_checker: null
  password_strength: ^0.2.0
  smooth_page_indicator: ^1.0.0+2
  blur:
  readmore:
  dot_navigation_bar:

dev_dependencies:
  flutter_launcher_icons: null

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
        - weight: 300
